### PR TITLE
Revert "Drop Urban Dictionary" then disable it for our IRC server instead

### PR DESCRIPTION
**Pull request by jdelic**
This reverts commit eab29350078ae0745d568cc2d026513988fe2628.
After merging #24 laterpay/puppet#22 will take care of disabling ud. Please note that anton is currently broken because the PR removing ud has not actually removed the import from `anton.modules.__init__`, so anton currently fails to start because of an ImportError.

### CODE REVIEW

**Comment by jdelic** [comment]
@doismellburning take a look, thx :)

**Comment by doismellburning** [comment]
After #24 we could pull out UD into a third party module, no? ;)

**Comment by haraball** [comment]
I love party modules :tada:

**Comment by doismellburning** [comment]
:P

**Comment by jdelic** [comment]
Is this marked PendingAnswer because it's really contentious to even have the module in anton? 

Of course you could pull it into an external module, but I don't have time to register, publish or maintain such a thing. So if the pure existence of the UD module is a problem, just delete this branch. 

The initial purpose of this branch was to fix the problem that the removal of UD broke anton completely because it was merged without any testing and so anton failed to build or start with an `ImportError`. That oversight has since been corrected in another PR.

**Pull request closed without merging**
