### PR TITLE
Fix the missing requirements-test.txt file in the package data.

### PR DESCRIPTION
**Pull request by jdelic**
@doismellburning anton's RPM build is currently broken because of this. Please review

### CODE REVIEW

**Comment by doismellburning** [comment]
We shouldn't be using `data_files` at all, especially not like that - it's for [placing data files outside of the package](https://packaging.python.org/en/latest/distributing.html?highlight=data_files#data-files) and just no...

**Comment by jdelic** [comment]
> We shouldn't be using data_files at all, especially not like that - it's for placing data files outside of the package and just no...

I agree. This will require some changes in the way `setup.py` uses the `requirements*.txt` files though. It reads them from the folder itself resides in. Otoh `requirements*.txt` files in a package folder are really uncommon too, but an opinionated, arguably better, layout is probably better than using `data_files`.

I would move `requirements*.txt` into the `anton` module and put appropriate "magic" into `setup.py` to find the location of the anton module and load the `requirements*.txt` files from there?

**Comment by jdelic** [comment]
`Procfile` then goes to `scripts/`, yes?

**Comment by doismellburning** [comment]
> Otoh requirements*.txt files in a package folder are really uncommon too

Yes, it's a hack because LaterPay's `buildhelpers` require applications to be packages - this is a bit grim and will hopefully go away soon (see BHELPERS-3)

That said, surprised the RPM packaging cares about `requirements-test.txt` in any way, plus the packaging build just passed, so lets leave this?

**Comment by jdelic** [comment]
>Yes, it's a hack because LaterPay's buildhelpers require applications to be packages - this is a bit grim and will hopefully go away soon (see BHELPERS-3)

I think it has a `setup.py` so people can install anton from pypi, not because of LaterPay's internal buildhelpers project. I think anton should stay installable from pypi, but that needs a `setup.py`.

> That said, surprised the RPM packaging cares about requirements-test.txt in any way, plus the RPM-packaging build just passed, so lets leave this?

It passed, but the RPM does not contain anton (it's a bug), see the exception in [build 91](https://jenkins.laterpay.net/job/applications.anton/91/console). The problem is that it installs `irc.anton` from pypi,laterpay.net which doesn't include `requirements-test.txt` so `setup.py` then fails. In other words `pip install irc.anton -i $LATERPAY_INDEX` is broken right now.

**Good news though**
I misunderstood the current problem. We shouldn't add files to `data_files` at all, as the reason for the failure was that `requirements-test.txt` was missing from `MANIFEST:in` and we are pushing `sdist` packages to `pypi.laterpay.net`. I fixed up this branch to remove `data_files` altogether and add `requirements-test.txt` to `MANIFEST.in` instead, which solves all of the above.

**Comment by doismellburning** [comment]
> I think it has a setup.py so people can install anton from pypi,

I don't think that's something we should support / encourage / etc.

However, we certainly need it internally for now, so yay, cheers for fixing! :)

**Pull request merged**
